# Show how formatted texts would look like in the current terminal
echo ""
echo "=== Basic ANSI Colors with Names ==="
echo -e "\e[30m Black (30) \e[0m"
echo -e "\e[31m Red (31) \e[0m"
echo -e "\e[32m Green (32) \e[0m"
echo -e "\e[33m Yellow (33) \e[0m"
echo -e "\e[34m Blue (34) \e[0m"
echo -e "\e[35m Magenta (35) \e[0m"
echo -e "\e[36m Cyan (36) \e[0m"
echo -e "\e[37m White (37) \e[0m"

echo ""
echo "=== Bright ANSI Colors ==="
echo -e "\e[90m Bright Black (90) \e[0m"
echo -e "\e[91m Bright Red (91) \e[0m"
echo -e "\e[92m Bright Green (92) \e[0m"
echo -e "\e[93m Bright Yellow (93) \e[0m"
echo -e "\e[94m Bright Blue (94) \e[0m"
echo -e "\e[95m Bright Magenta (95) \e[0m"
echo -e "\e[96m Bright Cyan (96) \e[0m"
echo -e "\e[97m Bright White (97) \e[0m"

echo ""
echo "=== Text Styles ==="
echo -e "\e[1m Bold \e[0m"
echo -e "\e[2m Dim \e[0m"
echo -e "\e[3m Italic \e[0m"
echo -e "\e[4m Underline \e[0m"
echo -e "\e[5m Blink \e[0m"
echo -e "\e[7m Reverse \e[0m"
echo -e "\e[9m Strikethrough \e[0m"
echo ""
